apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name }}
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | quote }}
